server:
  port: 10002

spring:
  data:
    redis:
      host: 127.0.0.1
      password: 123456
      database: 1

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: buni

buni:
  minio:
    endpoint: http://127.0.0.1:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucket: buni