spring:
  application:
    name: buni-file
  profiles:
    active: dev

# 以下为固定配置
# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# knife4j接口文档配置
knife4j:
  enable: true
springdoc:
  group-configs:
    - group: 文件管理
      packages-to-scan: com.buni.file.controller
