server:
  port: 10002

spring:
  data:
    redis:
      host: 127.0.0.1
      password: 123456
      database: 1

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: buni

# dubbo的配置
dubbo:
  application:
    name: file_dubbo_service
    qos-enable: false
  registry:
    id: file_dubbo_service
    address: nacos://127.0.0.1:8848?namespace=buni
  protocol:
    name: dubbo
    port: -1

buni:
  minio:
    endpoint: http://127.0.0.1:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucket: buni