server:
  port: 10000

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  data:
    redis:
      host: 127.0.0.1
      password: 123456
      database: 1

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: buni

    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000

      routes:
        - id: buni-user
          uri: lb://buni-user
          predicates: Path=/user/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                keyResolver: '#{@ipAddressKeyResolver}'
        - id: buni-file
          uri: lb://buni-file
          predicates: Path=/file/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                keyResolver: '#{@ipAddressKeyResolver}'
        - id: buni-bus
          uri: lb://buni-bus
          predicates: Path=/bus/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                keyResolver: '#{@ipAddressKeyResolver}'
