server:
  port: 10000

spring:
  data:
    redis:
      host: 127.0.0.1
      password: 123456
      database: 1
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: buni

# dubbo的配置
dubbo:
  application:
    name: gateway_dubbo_service
    qos-enable: false
  registry:
    id: gateway_dubbo_service
    address: nacos://127.0.0.1:8848?namespace=buni
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false
