server:
  port: 10000

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/buni?useSSL=false&useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      password: 123456
      db: 1

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: buni

    gateway:
      routes:
        - id: buni-user
          uri: lb://buni-user
          predicates: Path=/user/**
          filters:
            - StripPrefix=1
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000

buni:
  public-url:
    - /v1/login/POST
    - /v1/register/POST