server:
  port: 10003

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/buni?useSSL=false&useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      password: 123456
      database: 1

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: buni

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# dubbo的配置
dubbo:
  application:
    name: bus_dubbo_service
    qos-enable: false
  registry:
    id: bus_dubbo_service
    address: nacos://127.0.0.1:8848?namespace=buni
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false

knife4j:
  enable: true
springdoc:
  group-configs:
    - group: 消息管理
      packages-to-scan: com.buni.bus.controller

buni:
  salt: buni

