server:
  port: 10004

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/buni?useSSL=false&useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      password: 123456
      database: 1

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: buni

# dubbo的配置
dubbo:
  application:
    name: ai_dubbo_service
    qos-enable: false
  registry:
    id: ai_dubbo_service
    address: nacos://127.0.0.1:8848?namespace=buni
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false

buni:
  ai:
    qianfan:
      apiKey: Mu6l3kLYN7s6XFLD18homgZn
      secretKey: vrZc68YFLXq6xJCSQTEc1QAcQZKxIYeA
    spark:
      appId: ffa4749a
      apiKey: b45fb240f420c5319b895c804cef32ad
      apiSecret: YzI4YjU0YzIzMDhiNTFkM2MwYzI1NzNm